package raftcluster

import "time"

// CommandType selects which payload field of Command is populated.
type CommandType string

const (
	CommandCreateBot      CommandType = "create_bot"
	CommandUpdateBot      CommandType = "update_bot"
	CommandSetBotState    CommandType = "set_bot_state"
	CommandDeleteBot      CommandType = "delete_bot"
	CommandPutMessage     CommandType = "put_message"
	CommandUpdateDelivery CommandType = "update_delivery"
	// CommandCancelPending — backs Messaging.CancelPending ("отменить
	// неотправленное"). Not implemented as a plain
	// CommandUpdateDelivery from the gRPC layer on purpose: that would need a
	// separate GetMessage read to decide whether the message is still
	// PENDING/RETRYING before issuing the update, racing against a concurrent
	// delivery attempt reaching SENT/FAILED between the read and the Apply.
	// CancelPendingCommand instead carries just the idempotency_key and lets
	// FSM.applyCancelPending make the PENDING/RETRYING-only check atomically
	// inside the same Apply, identically on every replica.
	CommandCancelPending CommandType = "cancel_pending"

	// CommandUpdateChatMembership records one my_chat_member event
	// (chat_member_changed) into the replicated chat registry — see
	// ChatMembership and FSM.applyUpdateChatMembership. Applied by
	// internal/telegram's Runner right after publishing the same event to
	// its UpdateBus, so the registry and the live Messaging.Subscribe
	// stream both see it, from the same source event.
	CommandUpdateChatMembership CommandType = "update_chat_membership"
)

// Command is the unit of replication through the Raft log (команды на
// отправку, статусы доставки, принятые сообщения). It is JSON-encoded into raft.Log.Data by Node.Apply
// and decoded back by FSM.Apply. Exactly one payload field is non-nil,
// selected by Type; any other combination is rejected as ErrInvalidCommand.
//
// Determinism:
// FSM.Apply must compute the same resulting state on every replica given
// the same log entry, and replicas apply entries at different wall-clock
// moments. That means every value that could legitimately differ between
// replicas — the current time, a generated bot ID, randomness — MUST be
// decided by the caller *before* calling Node.Apply and carried inside the
// Command, never computed inside FSM.Apply itself. Every timestamp field
// below (CreatedAt/UpdatedAt/SentAt/NextRetryAt) and CreateBotCommand.ID
// are therefore inputs supplied by the caller (the gRPC layer),
// not values FSM.Apply invents.
type Command struct {
	Type CommandType `json:"type"`

	CreateBot      *CreateBotCommand      `json:"create_bot,omitempty"`
	UpdateBot      *UpdateBotCommand      `json:"update_bot,omitempty"`
	SetBotState    *SetBotStateCommand    `json:"set_bot_state,omitempty"`
	DeleteBot      *DeleteBotCommand      `json:"delete_bot,omitempty"`
	PutMessage     *PutMessageCommand     `json:"put_message,omitempty"`
	UpdateDelivery *UpdateDeliveryCommand `json:"update_delivery,omitempty"`
	CancelPending  *CancelPendingCommand  `json:"cancel_pending,omitempty"`

	UpdateChatMembership *UpdateChatMembershipCommand `json:"update_chat_membership,omitempty"`
}

// CreateBotCommand corresponds to BotAdmin.CreateBot. ID is
// generated by the caller (e.g. a UUID minted by the gRPC layer) so it is identical on every replica; FSM.Apply never
// generates identifiers itself.
type CreateBotCommand struct {
	ID          string       `json:"id"`
	DisplayName string       `json:"display_name"`
	Token       string       `json:"token"`
	Proxy       *ProxyConfig `json:"proxy,omitempty"` // nil = использовать умолчание узла
	CreatedAt   time.Time    `json:"created_at"`
}

// UpdateBotCommand corresponds to BotAdmin.UpdateBot ("токен, прокси,
// описание"). Token and DisplayName use the standard "nil = leave
// unchanged" convention. Proxy needs a second bit: ProxySet distinguishes
// "leave proxy unchanged" (false) from "set proxy to ProxyValue, which may
// itself be nil to revert to the node default" (true) — this mirrors the
// `optional ProxyConfig proxy` presence semantics in UpdateBotRequest.
type UpdateBotCommand struct {
	ID          string       `json:"id"`
	Token       *string      `json:"token,omitempty"`
	DisplayName *string      `json:"display_name,omitempty"`
	ProxySet    bool         `json:"proxy_set,omitempty"`
	ProxyValue  *ProxyConfig `json:"proxy_value,omitempty"`
	UpdatedAt   time.Time    `json:"updated_at"`
}

// SetBotStateCommand corresponds to BotAdmin.SetBotState and to the
// automatic lifecycle transitions (e.g. enabled → broken on an unrecoverable
// error). Restricting which transitions an external caller may request
// (the public RPC only allows ENABLED/DISABLED per the .proto comment) is
// the gRPC layer's job; FSM.Apply only enforces
// structural validity — the bot exists and is not already deleted.
type SetBotStateCommand struct {
	ID            string       `json:"id"`
	State         BotState     `json:"state"`
	FailureClass  FailureClass `json:"failure_class,omitempty"`  // осмысленно, когда State == BotStateBroken
	FailureReason string       `json:"failure_reason,omitempty"` // осмысленно, когда State == BotStateBroken
	UpdatedAt     time.Time    `json:"updated_at"`
}

// DeleteBotCommand corresponds to BotAdmin.DeleteBot. Deleting is a soft
// delete: the bot record and its message history remain ("процесс
// остановлен, история сообщений сохраняется"), only State becomes
// BotStateDeleted. Applying DeleteBot to an already-deleted bot is a
// no-op success, not an error (idempotent under retry).
type DeleteBotCommand struct {
	ID        string    `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

// PutMessageCommand corresponds to Messaging.Send recording a new outgoing
// message. IdempotencyKey is the idempotency mechanism: applying
// the same key twice must not create a second message — see FSM.Apply's
// handling of CommandPutMessage for the exact no-op semantics. The new
// message starts at DeliveryStatusPending with Retries = 0.
type PutMessageCommand struct {
	IdempotencyKey string    `json:"idempotency_key"`
	BotID          string    `json:"bot_id"`
	ChatID         int64     `json:"chat_id"`
	Text           string    `json:"text"`
	Buttons        []Button  `json:"buttons,omitempty"`
	Priority       Priority  `json:"priority"`
	CreatedAt      time.Time `json:"created_at"`
}

// UpdateDeliveryCommand corresponds to the delivery-status fields
// botmanager updates while attempting to send a message: status, retries, last_error,
// next_retry_at, sent_at. MessageID is the Telegram message id, known only
// after DeliveryStatusSent.
type UpdateDeliveryCommand struct {
	IdempotencyKey string         `json:"idempotency_key"`
	Status         DeliveryStatus `json:"status"`
	Retries        int            `json:"retries"`
	LastError      string         `json:"last_error,omitempty"`
	NextRetryAt    time.Time      `json:"next_retry_at,omitempty"`
	SentAt         time.Time      `json:"sent_at,omitempty"`
	MessageID      int64          `json:"message_id,omitempty"`
}

// CancelPendingCommand corresponds to Messaging.CancelPending ("отменить
// неотправленное"). See CommandCancelPending's doc comment for
// why this is its own command rather than a plain UpdateDeliveryCommand
// built by the gRPC layer. FSM.applyCancelPending transitions the message
// to DeliveryStatusCancelled only if it is currently
// DeliveryStatusPending/DeliveryStatusRetrying (or already Cancelled —
// idempotent no-op); SENT/FAILED are left untouched, matching
// CancelAck.cancelled = false in that case.
type CancelPendingCommand struct {
	IdempotencyKey string    `json:"idempotency_key"`
	CancelledAt    time.Time `json:"cancelled_at"`
}

// UpdateChatMembershipCommand corresponds to one my_chat_member update
// (chat_member_changed): the bot was added to/removed from ChatID.
// Title is best-effort (a live getChat call made by the caller before
// Apply — FSM.Apply never makes network calls);
// an empty Title on a later event does not erase a previously known one —
// see FSM.applyUpdateChatMembership.
type UpdateChatMembershipCommand struct {
	BotID     string    `json:"bot_id"`
	ChatID    int64     `json:"chat_id"`
	Title     string    `json:"title,omitempty"`
	IsMember  bool      `json:"is_member"`
	ChangedAt time.Time `json:"changed_at"`
}
