// botmanager gRPC contract.
//
// botmanager не знает ни о какой предметной области — только о ботах, чатах
// и сообщениях.
//
// Кодогенерация: см. Makefile, таргет `make proto`.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: botmanager.proto

package botmanagerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BotAdmin_CreateBot_FullMethodName           = "/botmanager.v1.BotAdmin/CreateBot"
	BotAdmin_UpdateBot_FullMethodName           = "/botmanager.v1.BotAdmin/UpdateBot"
	BotAdmin_SetBotState_FullMethodName         = "/botmanager.v1.BotAdmin/SetBotState"
	BotAdmin_DeleteBot_FullMethodName           = "/botmanager.v1.BotAdmin/DeleteBot"
	BotAdmin_ListBots_FullMethodName            = "/botmanager.v1.BotAdmin/ListBots"
	BotAdmin_GetBot_FullMethodName              = "/botmanager.v1.BotAdmin/GetBot"
	BotAdmin_GetChat_FullMethodName             = "/botmanager.v1.BotAdmin/GetChat"
	BotAdmin_VerifyInitData_FullMethodName      = "/botmanager.v1.BotAdmin/VerifyInitData"
	BotAdmin_ListChats_FullMethodName           = "/botmanager.v1.BotAdmin/ListChats"
	BotAdmin_GetUserProfilePhoto_FullMethodName = "/botmanager.v1.BotAdmin/GetUserProfilePhoto"
)

// BotAdminClient is the client API for BotAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BotAdminClient interface {
	CreateBot(ctx context.Context, in *CreateBotRequest, opts ...grpc.CallOption) (*Bot, error)
	UpdateBot(ctx context.Context, in *UpdateBotRequest, opts ...grpc.CallOption) (*Bot, error)
	SetBotState(ctx context.Context, in *SetBotStateRequest, opts ...grpc.CallOption) (*Bot, error)
	DeleteBot(ctx context.Context, in *DeleteBotRequest, opts ...grpc.CallOption) (*Empty, error)
	ListBots(ctx context.Context, in *ListBotsRequest, opts ...grpc.CallOption) (*BotList, error)
	GetBot(ctx context.Context, in *GetBotRequest, opts ...grpc.CallOption) (*Bot, error)
	GetChat(ctx context.Context, in *GetChatRequest, opts ...grpc.CallOption) (*Chat, error)
	VerifyInitData(ctx context.Context, in *VerifyInitDataRequest, opts ...grpc.CallOption) (*VerifyInitDataResult, error)
	// ListChats — различные чаты из истории сообщений бота,
	// с человекочитаемой подписью (название чата, если известно, иначе сам
	// id) — источник выпадающего списка в интерфейсе администратора вместо
	// ввода chat_id руками.
	ListChats(ctx context.Context, in *ListChatsRequest, opts ...grpc.CallOption) (*ChatList, error)
	// GetUserProfilePhoto — текущая фотография профиля пользователя
	// (аватар), см. комментарии на сообщениях.
	GetUserProfilePhoto(ctx context.Context, in *GetUserProfilePhotoRequest, opts ...grpc.CallOption) (*GetUserProfilePhotoResult, error)
}

type botAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewBotAdminClient(cc grpc.ClientConnInterface) BotAdminClient {
	return &botAdminClient{cc}
}

func (c *botAdminClient) CreateBot(ctx context.Context, in *CreateBotRequest, opts ...grpc.CallOption) (*Bot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Bot)
	err := c.cc.Invoke(ctx, BotAdmin_CreateBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botAdminClient) UpdateBot(ctx context.Context, in *UpdateBotRequest, opts ...grpc.CallOption) (*Bot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Bot)
	err := c.cc.Invoke(ctx, BotAdmin_UpdateBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botAdminClient) SetBotState(ctx context.Context, in *SetBotStateRequest, opts ...grpc.CallOption) (*Bot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Bot)
	err := c.cc.Invoke(ctx, BotAdmin_SetBotState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botAdminClient) DeleteBot(ctx context.Context, in *DeleteBotRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, BotAdmin_DeleteBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botAdminClient) ListBots(ctx context.Context, in *ListBotsRequest, opts ...grpc.CallOption) (*BotList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BotList)
	err := c.cc.Invoke(ctx, BotAdmin_ListBots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botAdminClient) GetBot(ctx context.Context, in *GetBotRequest, opts ...grpc.CallOption) (*Bot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Bot)
	err := c.cc.Invoke(ctx, BotAdmin_GetBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botAdminClient) GetChat(ctx context.Context, in *GetChatRequest, opts ...grpc.CallOption) (*Chat, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Chat)
	err := c.cc.Invoke(ctx, BotAdmin_GetChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botAdminClient) VerifyInitData(ctx context.Context, in *VerifyInitDataRequest, opts ...grpc.CallOption) (*VerifyInitDataResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyInitDataResult)
	err := c.cc.Invoke(ctx, BotAdmin_VerifyInitData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botAdminClient) ListChats(ctx context.Context, in *ListChatsRequest, opts ...grpc.CallOption) (*ChatList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatList)
	err := c.cc.Invoke(ctx, BotAdmin_ListChats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botAdminClient) GetUserProfilePhoto(ctx context.Context, in *GetUserProfilePhotoRequest, opts ...grpc.CallOption) (*GetUserProfilePhotoResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserProfilePhotoResult)
	err := c.cc.Invoke(ctx, BotAdmin_GetUserProfilePhoto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BotAdminServer is the server API for BotAdmin service.
// All implementations must embed UnimplementedBotAdminServer
// for forward compatibility.
type BotAdminServer interface {
	CreateBot(context.Context, *CreateBotRequest) (*Bot, error)
	UpdateBot(context.Context, *UpdateBotRequest) (*Bot, error)
	SetBotState(context.Context, *SetBotStateRequest) (*Bot, error)
	DeleteBot(context.Context, *DeleteBotRequest) (*Empty, error)
	ListBots(context.Context, *ListBotsRequest) (*BotList, error)
	GetBot(context.Context, *GetBotRequest) (*Bot, error)
	GetChat(context.Context, *GetChatRequest) (*Chat, error)
	VerifyInitData(context.Context, *VerifyInitDataRequest) (*VerifyInitDataResult, error)
	// ListChats — различные чаты из истории сообщений бота,
	// с человекочитаемой подписью (название чата, если известно, иначе сам
	// id) — источник выпадающего списка в интерфейсе администратора вместо
	// ввода chat_id руками.
	ListChats(context.Context, *ListChatsRequest) (*ChatList, error)
	// GetUserProfilePhoto — текущая фотография профиля пользователя
	// (аватар), см. комментарии на сообщениях.
	GetUserProfilePhoto(context.Context, *GetUserProfilePhotoRequest) (*GetUserProfilePhotoResult, error)
	mustEmbedUnimplementedBotAdminServer()
}

// UnimplementedBotAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBotAdminServer struct{}

func (UnimplementedBotAdminServer) CreateBot(context.Context, *CreateBotRequest) (*Bot, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBot not implemented")
}
func (UnimplementedBotAdminServer) UpdateBot(context.Context, *UpdateBotRequest) (*Bot, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBot not implemented")
}
func (UnimplementedBotAdminServer) SetBotState(context.Context, *SetBotStateRequest) (*Bot, error) {
	return nil, status.Error(codes.Unimplemented, "method SetBotState not implemented")
}
func (UnimplementedBotAdminServer) DeleteBot(context.Context, *DeleteBotRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBot not implemented")
}
func (UnimplementedBotAdminServer) ListBots(context.Context, *ListBotsRequest) (*BotList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBots not implemented")
}
func (UnimplementedBotAdminServer) GetBot(context.Context, *GetBotRequest) (*Bot, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBot not implemented")
}
func (UnimplementedBotAdminServer) GetChat(context.Context, *GetChatRequest) (*Chat, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChat not implemented")
}
func (UnimplementedBotAdminServer) VerifyInitData(context.Context, *VerifyInitDataRequest) (*VerifyInitDataResult, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyInitData not implemented")
}
func (UnimplementedBotAdminServer) ListChats(context.Context, *ListChatsRequest) (*ChatList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListChats not implemented")
}
func (UnimplementedBotAdminServer) GetUserProfilePhoto(context.Context, *GetUserProfilePhotoRequest) (*GetUserProfilePhotoResult, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserProfilePhoto not implemented")
}
func (UnimplementedBotAdminServer) mustEmbedUnimplementedBotAdminServer() {}
func (UnimplementedBotAdminServer) testEmbeddedByValue()                  {}

// UnsafeBotAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BotAdminServer will
// result in compilation errors.
type UnsafeBotAdminServer interface {
	mustEmbedUnimplementedBotAdminServer()
}

func RegisterBotAdminServer(s grpc.ServiceRegistrar, srv BotAdminServer) {
	// If the following call panics, it indicates UnimplementedBotAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BotAdmin_ServiceDesc, srv)
}

func _BotAdmin_CreateBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotAdminServer).CreateBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotAdmin_CreateBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotAdminServer).CreateBot(ctx, req.(*CreateBotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotAdmin_UpdateBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotAdminServer).UpdateBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotAdmin_UpdateBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotAdminServer).UpdateBot(ctx, req.(*UpdateBotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotAdmin_SetBotState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBotStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotAdminServer).SetBotState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotAdmin_SetBotState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotAdminServer).SetBotState(ctx, req.(*SetBotStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotAdmin_DeleteBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotAdminServer).DeleteBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotAdmin_DeleteBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotAdminServer).DeleteBot(ctx, req.(*DeleteBotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotAdmin_ListBots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotAdminServer).ListBots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotAdmin_ListBots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotAdminServer).ListBots(ctx, req.(*ListBotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotAdmin_GetBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotAdminServer).GetBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotAdmin_GetBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotAdminServer).GetBot(ctx, req.(*GetBotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotAdmin_GetChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotAdminServer).GetChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotAdmin_GetChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotAdminServer).GetChat(ctx, req.(*GetChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotAdmin_VerifyInitData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyInitDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotAdminServer).VerifyInitData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotAdmin_VerifyInitData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotAdminServer).VerifyInitData(ctx, req.(*VerifyInitDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotAdmin_ListChats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotAdminServer).ListChats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotAdmin_ListChats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotAdminServer).ListChats(ctx, req.(*ListChatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotAdmin_GetUserProfilePhoto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserProfilePhotoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotAdminServer).GetUserProfilePhoto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotAdmin_GetUserProfilePhoto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotAdminServer).GetUserProfilePhoto(ctx, req.(*GetUserProfilePhotoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BotAdmin_ServiceDesc is the grpc.ServiceDesc for BotAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BotAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "botmanager.v1.BotAdmin",
	HandlerType: (*BotAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBot",
			Handler:    _BotAdmin_CreateBot_Handler,
		},
		{
			MethodName: "UpdateBot",
			Handler:    _BotAdmin_UpdateBot_Handler,
		},
		{
			MethodName: "SetBotState",
			Handler:    _BotAdmin_SetBotState_Handler,
		},
		{
			MethodName: "DeleteBot",
			Handler:    _BotAdmin_DeleteBot_Handler,
		},
		{
			MethodName: "ListBots",
			Handler:    _BotAdmin_ListBots_Handler,
		},
		{
			MethodName: "GetBot",
			Handler:    _BotAdmin_GetBot_Handler,
		},
		{
			MethodName: "GetChat",
			Handler:    _BotAdmin_GetChat_Handler,
		},
		{
			MethodName: "VerifyInitData",
			Handler:    _BotAdmin_VerifyInitData_Handler,
		},
		{
			MethodName: "ListChats",
			Handler:    _BotAdmin_ListChats_Handler,
		},
		{
			MethodName: "GetUserProfilePhoto",
			Handler:    _BotAdmin_GetUserProfilePhoto_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "botmanager.proto",
}

const (
	Messaging_Send_FullMethodName           = "/botmanager.v1.Messaging/Send"
	Messaging_SendBatch_FullMethodName      = "/botmanager.v1.Messaging/SendBatch"
	Messaging_EditMessage_FullMethodName    = "/botmanager.v1.Messaging/EditMessage"
	Messaging_DeleteMessage_FullMethodName  = "/botmanager.v1.Messaging/DeleteMessage"
	Messaging_PinMessage_FullMethodName     = "/botmanager.v1.Messaging/PinMessage"
	Messaging_UnpinMessage_FullMethodName   = "/botmanager.v1.Messaging/UnpinMessage"
	Messaging_CancelPending_FullMethodName  = "/botmanager.v1.Messaging/CancelPending"
	Messaging_AnswerCallback_FullMethodName = "/botmanager.v1.Messaging/AnswerCallback"
	Messaging_GetMessage_FullMethodName     = "/botmanager.v1.Messaging/GetMessage"
	Messaging_GetMessages_FullMethodName    = "/botmanager.v1.Messaging/GetMessages"
	Messaging_ListMessages_FullMethodName   = "/botmanager.v1.Messaging/ListMessages"
	Messaging_Subscribe_FullMethodName      = "/botmanager.v1.Messaging/Subscribe"
)

// MessagingClient is the client API for Messaging service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessagingClient interface {
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendAck, error)
	SendBatch(ctx context.Context, in *SendBatchRequest, opts ...grpc.CallOption) (*SendBatchAck, error)
	EditMessage(ctx context.Context, in *EditMessageRequest, opts ...grpc.CallOption) (*SendAck, error)
	DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*Empty, error)
	PinMessage(ctx context.Context, in *PinMessageRequest, opts ...grpc.CallOption) (*Empty, error)
	UnpinMessage(ctx context.Context, in *UnpinMessageRequest, opts ...grpc.CallOption) (*Empty, error)
	CancelPending(ctx context.Context, in *CancelPendingRequest, opts ...grpc.CallOption) (*CancelAck, error)
	AnswerCallback(ctx context.Context, in *AnswerCallbackRequest, opts ...grpc.CallOption) (*Empty, error)
	GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*Message, error)
	GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*MessageList, error)
	ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*MessageList, error)
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Update], error)
}

type messagingClient struct {
	cc grpc.ClientConnInterface
}

func NewMessagingClient(cc grpc.ClientConnInterface) MessagingClient {
	return &messagingClient{cc}
}

func (c *messagingClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendAck)
	err := c.cc.Invoke(ctx, Messaging_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingClient) SendBatch(ctx context.Context, in *SendBatchRequest, opts ...grpc.CallOption) (*SendBatchAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendBatchAck)
	err := c.cc.Invoke(ctx, Messaging_SendBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingClient) EditMessage(ctx context.Context, in *EditMessageRequest, opts ...grpc.CallOption) (*SendAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendAck)
	err := c.cc.Invoke(ctx, Messaging_EditMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingClient) DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Messaging_DeleteMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingClient) PinMessage(ctx context.Context, in *PinMessageRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Messaging_PinMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingClient) UnpinMessage(ctx context.Context, in *UnpinMessageRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Messaging_UnpinMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingClient) CancelPending(ctx context.Context, in *CancelPendingRequest, opts ...grpc.CallOption) (*CancelAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelAck)
	err := c.cc.Invoke(ctx, Messaging_CancelPending_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingClient) AnswerCallback(ctx context.Context, in *AnswerCallbackRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Messaging_AnswerCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingClient) GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, Messaging_GetMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingClient) GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*MessageList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageList)
	err := c.cc.Invoke(ctx, Messaging_GetMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingClient) ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*MessageList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageList)
	err := c.cc.Invoke(ctx, Messaging_ListMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Update], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Messaging_ServiceDesc.Streams[0], Messaging_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, Update]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Messaging_SubscribeClient = grpc.ServerStreamingClient[Update]

// MessagingServer is the server API for Messaging service.
// All implementations must embed UnimplementedMessagingServer
// for forward compatibility.
type MessagingServer interface {
	Send(context.Context, *SendRequest) (*SendAck, error)
	SendBatch(context.Context, *SendBatchRequest) (*SendBatchAck, error)
	EditMessage(context.Context, *EditMessageRequest) (*SendAck, error)
	DeleteMessage(context.Context, *DeleteMessageRequest) (*Empty, error)
	PinMessage(context.Context, *PinMessageRequest) (*Empty, error)
	UnpinMessage(context.Context, *UnpinMessageRequest) (*Empty, error)
	CancelPending(context.Context, *CancelPendingRequest) (*CancelAck, error)
	AnswerCallback(context.Context, *AnswerCallbackRequest) (*Empty, error)
	GetMessage(context.Context, *GetMessageRequest) (*Message, error)
	GetMessages(context.Context, *GetMessagesRequest) (*MessageList, error)
	ListMessages(context.Context, *ListMessagesRequest) (*MessageList, error)
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Update]) error
	mustEmbedUnimplementedMessagingServer()
}

// UnimplementedMessagingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessagingServer struct{}

func (UnimplementedMessagingServer) Send(context.Context, *SendRequest) (*SendAck, error) {
	return nil, status.Error(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedMessagingServer) SendBatch(context.Context, *SendBatchRequest) (*SendBatchAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SendBatch not implemented")
}
func (UnimplementedMessagingServer) EditMessage(context.Context, *EditMessageRequest) (*SendAck, error) {
	return nil, status.Error(codes.Unimplemented, "method EditMessage not implemented")
}
func (UnimplementedMessagingServer) DeleteMessage(context.Context, *DeleteMessageRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMessage not implemented")
}
func (UnimplementedMessagingServer) PinMessage(context.Context, *PinMessageRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PinMessage not implemented")
}
func (UnimplementedMessagingServer) UnpinMessage(context.Context, *UnpinMessageRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UnpinMessage not implemented")
}
func (UnimplementedMessagingServer) CancelPending(context.Context, *CancelPendingRequest) (*CancelAck, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelPending not implemented")
}
func (UnimplementedMessagingServer) AnswerCallback(context.Context, *AnswerCallbackRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AnswerCallback not implemented")
}
func (UnimplementedMessagingServer) GetMessage(context.Context, *GetMessageRequest) (*Message, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMessage not implemented")
}
func (UnimplementedMessagingServer) GetMessages(context.Context, *GetMessagesRequest) (*MessageList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMessages not implemented")
}
func (UnimplementedMessagingServer) ListMessages(context.Context, *ListMessagesRequest) (*MessageList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMessages not implemented")
}
func (UnimplementedMessagingServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Update]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedMessagingServer) mustEmbedUnimplementedMessagingServer() {}
func (UnimplementedMessagingServer) testEmbeddedByValue()                   {}

// UnsafeMessagingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessagingServer will
// result in compilation errors.
type UnsafeMessagingServer interface {
	mustEmbedUnimplementedMessagingServer()
}

func RegisterMessagingServer(s grpc.ServiceRegistrar, srv MessagingServer) {
	// If the following call panics, it indicates UnimplementedMessagingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Messaging_ServiceDesc, srv)
}

func _Messaging_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Messaging_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServer).Send(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messaging_SendBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServer).SendBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Messaging_SendBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServer).SendBatch(ctx, req.(*SendBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messaging_EditMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServer).EditMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Messaging_EditMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServer).EditMessage(ctx, req.(*EditMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messaging_DeleteMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServer).DeleteMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Messaging_DeleteMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServer).DeleteMessage(ctx, req.(*DeleteMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messaging_PinMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PinMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServer).PinMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Messaging_PinMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServer).PinMessage(ctx, req.(*PinMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messaging_UnpinMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnpinMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServer).UnpinMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Messaging_UnpinMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServer).UnpinMessage(ctx, req.(*UnpinMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messaging_CancelPending_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelPendingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServer).CancelPending(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Messaging_CancelPending_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServer).CancelPending(ctx, req.(*CancelPendingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messaging_AnswerCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServer).AnswerCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Messaging_AnswerCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServer).AnswerCallback(ctx, req.(*AnswerCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messaging_GetMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServer).GetMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Messaging_GetMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServer).GetMessage(ctx, req.(*GetMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messaging_GetMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServer).GetMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Messaging_GetMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServer).GetMessages(ctx, req.(*GetMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messaging_ListMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServer).ListMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Messaging_ListMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServer).ListMessages(ctx, req.(*ListMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messaging_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MessagingServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, Update]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Messaging_SubscribeServer = grpc.ServerStreamingServer[Update]

// Messaging_ServiceDesc is the grpc.ServiceDesc for Messaging service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Messaging_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "botmanager.v1.Messaging",
	HandlerType: (*MessagingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _Messaging_Send_Handler,
		},
		{
			MethodName: "SendBatch",
			Handler:    _Messaging_SendBatch_Handler,
		},
		{
			MethodName: "EditMessage",
			Handler:    _Messaging_EditMessage_Handler,
		},
		{
			MethodName: "DeleteMessage",
			Handler:    _Messaging_DeleteMessage_Handler,
		},
		{
			MethodName: "PinMessage",
			Handler:    _Messaging_PinMessage_Handler,
		},
		{
			MethodName: "UnpinMessage",
			Handler:    _Messaging_UnpinMessage_Handler,
		},
		{
			MethodName: "CancelPending",
			Handler:    _Messaging_CancelPending_Handler,
		},
		{
			MethodName: "AnswerCallback",
			Handler:    _Messaging_AnswerCallback_Handler,
		},
		{
			MethodName: "GetMessage",
			Handler:    _Messaging_GetMessage_Handler,
		},
		{
			MethodName: "GetMessages",
			Handler:    _Messaging_GetMessages_Handler,
		},
		{
			MethodName: "ListMessages",
			Handler:    _Messaging_ListMessages_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _Messaging_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "botmanager.proto",
}

const (
	Maintenance_GetClusterStatus_FullMethodName   = "/botmanager.v1.Maintenance/GetClusterStatus"
	Maintenance_ExportState_FullMethodName        = "/botmanager.v1.Maintenance/ExportState"
	Maintenance_TransferLeadership_FullMethodName = "/botmanager.v1.Maintenance/TransferLeadership"
	Maintenance_PingTelegram_FullMethodName       = "/botmanager.v1.Maintenance/PingTelegram"
	Maintenance_AddNode_FullMethodName            = "/botmanager.v1.Maintenance/AddNode"
	Maintenance_RemoveNode_FullMethodName         = "/botmanager.v1.Maintenance/RemoveNode"
)

// MaintenanceClient is the client API for Maintenance service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MaintenanceClient interface {
	GetClusterStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ClusterStatus, error)
	ExportState(ctx context.Context, in *ExportStateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Chunk], error)
	// TransferLeadership назначает мастером конкретный узел
	// поверх штатной передачи лидерства Raft (RaftCluster.LeadershipTransferToServer),
	// не самодельных выборов. NOT_FOUND — узел неизвестен кластеру,
	// UNAVAILABLE — передача не удалась.
	TransferLeadership(ctx context.Context, in *TransferLeadershipRequest, opts ...grpc.CallOption) (*ClusterStatus, error)
	// PingTelegram проверяет доступность Telegram API со стороны botmanager,
	// в том числе через настроенный прокси — отвечает на
	// вопрос "это у нас сеть или у Telegram". Таймаут —
	// CLAUDE.md, раздел "PingTelegram".
	PingTelegram(ctx context.Context, in *PingTelegramRequest, opts ...grpc.CallOption) (*PingResult, error)
	// AddNode/RemoveNode меняют состав Raft-кластера. Как и любая запись,
	// выполняются на лидере (вызов на другом узле пересылается лидеру).
	AddNode(ctx context.Context, in *AddNodeRequest, opts ...grpc.CallOption) (*ClusterStatus, error)
	RemoveNode(ctx context.Context, in *RemoveNodeRequest, opts ...grpc.CallOption) (*ClusterStatus, error)
}

type maintenanceClient struct {
	cc grpc.ClientConnInterface
}

func NewMaintenanceClient(cc grpc.ClientConnInterface) MaintenanceClient {
	return &maintenanceClient{cc}
}

func (c *maintenanceClient) GetClusterStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ClusterStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterStatus)
	err := c.cc.Invoke(ctx, Maintenance_GetClusterStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintenanceClient) ExportState(ctx context.Context, in *ExportStateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Chunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Maintenance_ServiceDesc.Streams[0], Maintenance_ExportState_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExportStateRequest, Chunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Maintenance_ExportStateClient = grpc.ServerStreamingClient[Chunk]

func (c *maintenanceClient) TransferLeadership(ctx context.Context, in *TransferLeadershipRequest, opts ...grpc.CallOption) (*ClusterStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterStatus)
	err := c.cc.Invoke(ctx, Maintenance_TransferLeadership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintenanceClient) PingTelegram(ctx context.Context, in *PingTelegramRequest, opts ...grpc.CallOption) (*PingResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResult)
	err := c.cc.Invoke(ctx, Maintenance_PingTelegram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintenanceClient) AddNode(ctx context.Context, in *AddNodeRequest, opts ...grpc.CallOption) (*ClusterStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterStatus)
	err := c.cc.Invoke(ctx, Maintenance_AddNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintenanceClient) RemoveNode(ctx context.Context, in *RemoveNodeRequest, opts ...grpc.CallOption) (*ClusterStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterStatus)
	err := c.cc.Invoke(ctx, Maintenance_RemoveNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MaintenanceServer is the server API for Maintenance service.
// All implementations must embed UnimplementedMaintenanceServer
// for forward compatibility.
type MaintenanceServer interface {
	GetClusterStatus(context.Context, *Empty) (*ClusterStatus, error)
	ExportState(*ExportStateRequest, grpc.ServerStreamingServer[Chunk]) error
	// TransferLeadership назначает мастером конкретный узел
	// поверх штатной передачи лидерства Raft (RaftCluster.LeadershipTransferToServer),
	// не самодельных выборов. NOT_FOUND — узел неизвестен кластеру,
	// UNAVAILABLE — передача не удалась.
	TransferLeadership(context.Context, *TransferLeadershipRequest) (*ClusterStatus, error)
	// PingTelegram проверяет доступность Telegram API со стороны botmanager,
	// в том числе через настроенный прокси — отвечает на
	// вопрос "это у нас сеть или у Telegram". Таймаут —
	// CLAUDE.md, раздел "PingTelegram".
	PingTelegram(context.Context, *PingTelegramRequest) (*PingResult, error)
	// AddNode/RemoveNode меняют состав Raft-кластера. Как и любая запись,
	// выполняются на лидере (вызов на другом узле пересылается лидеру).
	AddNode(context.Context, *AddNodeRequest) (*ClusterStatus, error)
	RemoveNode(context.Context, *RemoveNodeRequest) (*ClusterStatus, error)
	mustEmbedUnimplementedMaintenanceServer()
}

// UnimplementedMaintenanceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMaintenanceServer struct{}

func (UnimplementedMaintenanceServer) GetClusterStatus(context.Context, *Empty) (*ClusterStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClusterStatus not implemented")
}
func (UnimplementedMaintenanceServer) ExportState(*ExportStateRequest, grpc.ServerStreamingServer[Chunk]) error {
	return status.Error(codes.Unimplemented, "method ExportState not implemented")
}
func (UnimplementedMaintenanceServer) TransferLeadership(context.Context, *TransferLeadershipRequest) (*ClusterStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferLeadership not implemented")
}
func (UnimplementedMaintenanceServer) PingTelegram(context.Context, *PingTelegramRequest) (*PingResult, error) {
	return nil, status.Error(codes.Unimplemented, "method PingTelegram not implemented")
}
func (UnimplementedMaintenanceServer) AddNode(context.Context, *AddNodeRequest) (*ClusterStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method AddNode not implemented")
}
func (UnimplementedMaintenanceServer) RemoveNode(context.Context, *RemoveNodeRequest) (*ClusterStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveNode not implemented")
}
func (UnimplementedMaintenanceServer) mustEmbedUnimplementedMaintenanceServer() {}
func (UnimplementedMaintenanceServer) testEmbeddedByValue()                     {}

// UnsafeMaintenanceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MaintenanceServer will
// result in compilation errors.
type UnsafeMaintenanceServer interface {
	mustEmbedUnimplementedMaintenanceServer()
}

func RegisterMaintenanceServer(s grpc.ServiceRegistrar, srv MaintenanceServer) {
	// If the following call panics, it indicates UnimplementedMaintenanceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Maintenance_ServiceDesc, srv)
}

func _Maintenance_GetClusterStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintenanceServer).GetClusterStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maintenance_GetClusterStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintenanceServer).GetClusterStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maintenance_ExportState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExportStateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MaintenanceServer).ExportState(m, &grpc.GenericServerStream[ExportStateRequest, Chunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Maintenance_ExportStateServer = grpc.ServerStreamingServer[Chunk]

func _Maintenance_TransferLeadership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferLeadershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintenanceServer).TransferLeadership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maintenance_TransferLeadership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintenanceServer).TransferLeadership(ctx, req.(*TransferLeadershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maintenance_PingTelegram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingTelegramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintenanceServer).PingTelegram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maintenance_PingTelegram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintenanceServer).PingTelegram(ctx, req.(*PingTelegramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maintenance_AddNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintenanceServer).AddNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maintenance_AddNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintenanceServer).AddNode(ctx, req.(*AddNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maintenance_RemoveNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintenanceServer).RemoveNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maintenance_RemoveNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintenanceServer).RemoveNode(ctx, req.(*RemoveNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Maintenance_ServiceDesc is the grpc.ServiceDesc for Maintenance service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Maintenance_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "botmanager.v1.Maintenance",
	HandlerType: (*MaintenanceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClusterStatus",
			Handler:    _Maintenance_GetClusterStatus_Handler,
		},
		{
			MethodName: "TransferLeadership",
			Handler:    _Maintenance_TransferLeadership_Handler,
		},
		{
			MethodName: "PingTelegram",
			Handler:    _Maintenance_PingTelegram_Handler,
		},
		{
			MethodName: "AddNode",
			Handler:    _Maintenance_AddNode_Handler,
		},
		{
			MethodName: "RemoveNode",
			Handler:    _Maintenance_RemoveNode_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExportState",
			Handler:       _Maintenance_ExportState_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "botmanager.proto",
}
